In [1]:
import numpy as np 
import pandas as pd 

data=pd.read_csv("diamonds_data.csv")
data.info()

#count value
#data["z"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 27 columns):
Unnamed: 0        53940 non-null int64
carat             53940 non-null float64
cut_Fair          53940 non-null int64
cut_Good          53940 non-null int64
cut_Ideal         53940 non-null int64
cut_Premium       53940 non-null int64
cut_Very Good     53940 non-null int64
color_D           53940 non-null int64
color_E           53940 non-null int64
color_F           53940 non-null int64
color_G           53940 non-null int64
color_H           53940 non-null int64
color_I           53940 non-null int64
color_J           53940 non-null int64
clarity_I1        53940 non-null int64
clarity_IF        53940 non-null int64
clarity_SI1       53940 non-null int64
clarity_SI2       53940 non-null int64
clarity_VS1       53940 non-null int64
clarity_VS2       53940 non-null int64
clarity_VVS1      53940 non-null int64
clarity_VVS2      53940 non-null int64
cut               53940 non-nul

In [2]:
data.head(3)

Unnamed: 0  carat  cut_Fair  cut_Good  cut_Ideal  cut_Premium  \
0           0   0.23         0         0          1            0   
1           1   0.21         0         0          0            1   
2           2   0.23         0         1          0            0   

   cut_Very Good  color_D  color_E  color_F       ...        clarity_SI2  \
0              0        0        1        0       ...                  1   
1              0        0        1        0       ...                  0   
2              0        0        1        0       ...                  0   

   clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2  cut  color  clarity  \
0            0            0             0             0    1      2        7   
1            0            0             0             0    2      2        6   
2            1            0             0             0    4      2        4   

   priceperpoint  carat_discrete  
0              1               1  
1              1               1  
2              1               1  

[3 rows x 27 columns]

In [3]:
data=data.drop(
data.columns[0],axis=1)
data.head(3)

carat  cut_Fair  cut_Good  cut_Ideal  cut_Premium  cut_Very Good  color_D  \
0   0.23         0         0          1            0              0        0   
1   0.21         0         0          0            1              0        0   
2   0.23         0         1          0            0              0        0   

   color_E  color_F  color_G       ...        clarity_SI2  clarity_VS1  \
0        1        0        0       ...                  1            0   
1        1        0        0       ...                  0            0   
2        1        0        0       ...                  0            1   

   clarity_VS2  clarity_VVS1  clarity_VVS2  cut  color  clarity  \
0            0             0             0    1      2        7   
1            0             0             0    2      2        6   
2            0             0             0    4      2        4   

   priceperpoint  carat_discrete  
0              1               1  
1              1               1  
2              1               1  

[3 rows x 26 columns]

In [4]:
# split
#cut data set into train and target data
from sklearn.model_selection import train_test_split
sampled_data=pd.concat([data[data['priceperpoint']==4].sample(7000),data[data['priceperpoint']==3].sample(7000),data[data['priceperpoint']==2].sample(7000),data[data['priceperpoint']==1].sample(7000)],ignore_index=True)

print(sampled_data['priceperpoint'].value_counts())
X=sampled_data.drop(['priceperpoint'], axis=1)
y=sampled_data['priceperpoint']
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.15, random_state=0, stratify=None)
print("training \n",y_train.value_counts())
print("testing \n",y_test.value_counts())

4    7000
3    7000
2    7000
1    7000
Name: priceperpoint, dtype: int64
training 
 1    5968
2    5953
4    5947
3    5932
Name: priceperpoint, dtype: int64
testing 
 3    1068
4    1053
2    1047
1    1032
Name: priceperpoint, dtype: int64


# 全部特徵下去跑

In [10]:
#Naive Bayer Classification
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

gaussian = GaussianNB() 
gaussian.fit(X_train, y_train)  
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)
print("train data accuracy:",acc_gaussian)

predict=gaussian.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predict))

acc_gaussian = round(gaussian.score(X_test, y_test) * 100, 2)
print("test data accuracy:",acc_gaussian)

from sklearn.metrics import classification_report
print(classification_report(y_test,predict))


precision=precision_score(y_test,predict,average='weighted')
recall=recall_score(y_test,predict,average='weighted')
f1=f1_score(y_test,predict,average='weighted')
print("precision:",precision, "\nrecall:", recall, "\nf1:", f1)

train data accuracy: 69.78
[[969  52  11   0]
 [383 443 211  10]
 [  0 186 730 152]
 [  1  39 260 753]]
test data accuracy: 68.93
              precision    recall  f1-score   support

           1       0.72      0.94      0.81      1032
           2       0.62      0.42      0.50      1047
           3       0.60      0.68      0.64      1068
           4       0.82      0.72      0.77      1053

    accuracy                           0.69      4200
   macro avg       0.69      0.69      0.68      4200
weighted avg       0.69      0.69      0.68      4200

precision: 0.688841568105017 
recall: 0.6892857142857143 
f1: 0.6793473863010258


In [8]:
#Naive Bayer Classification MultinomialNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

gaussian = MultinomialNB() 
gaussian.fit(X_train, y_train)  
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)
print("train data accuracy:",acc_gaussian)

predict=gaussian.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predict))

acc_gaussian = round(gaussian.score(X_test, y_test) * 100, 2)
print("test data accuracy:",acc_gaussian)

from sklearn.metrics import classification_report
print(classification_report(y_test,predict))

precision=precision_score(y_test,predict,average='weighted')
recall=recall_score(y_test,predict,average='weighted')
f1=f1_score(y_test,predict,average='weighted')
print("precision:",precision, "\nrecall:", recall, "\nf1:", f1)

train data accuracy: 62.77
[[744 259  29   0]
 [173 516 268  90]
 [ 17 124 649 278]
 [  0  22 357 674]]
test data accuracy: 61.5
              precision    recall  f1-score   support

           1       0.80      0.72      0.76      1032
           2       0.56      0.49      0.52      1047
           3       0.50      0.61      0.55      1068
           4       0.65      0.64      0.64      1053

    accuracy                           0.61      4200
   macro avg       0.63      0.62      0.62      4200
weighted avg       0.62      0.61      0.62      4200

precision: 0.624219790340803 
recall: 0.615 
f1: 0.6172230424415215


SVM
Classification
Sklearn.svm
LinearSVC()
Sklearn.svm
SVC()

In [9]:
#SVM
from sklearn.svm import SVC, LinearSVC

linear_svc = LinearSVC(penalty='l1',dual=False)
linear_svc.fit(X_train, y_train)
acc_linear_svc = round(linear_svc.score(X_train, y_train) * 100, 2)
print("train data accuracy:",acc_linear_svc)


predict = linear_svc.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predict))

acc_linear_svc = round(linear_svc.score(X_test, y_test) * 100, 2)
print("test data accuracy:",acc_linear_svc)

from sklearn.metrics import classification_report
print(classification_report(y_test,predict))

precision=precision_score(y_test,predict,average='weighted')
recall=recall_score(y_test,predict,average='weighted')
f1=f1_score(y_test,predict,average='weighted')
print("precision:",precision, "\nrecall:", recall, "\nf1:", f1)

train data accuracy: 77.35
[[ 997   33    2    0]
 [ 225  557  263    2]
 [   0  215  715  138]
 [   0    9   43 1001]]
test data accuracy: 77.86
              precision    recall  f1-score   support

           1       0.82      0.97      0.88      1032
           2       0.68      0.53      0.60      1047
           3       0.70      0.67      0.68      1068
           4       0.88      0.95      0.91      1053

    accuracy                           0.78      4200
   macro avg       0.77      0.78      0.77      4200
weighted avg       0.77      0.78      0.77      4200

precision: 0.7687306929141672 
recall: 0.7785714285714286 
f1: 0.7692698595798646


C:\Users\user\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


# feature importance

# 看連續數值+類別

In [35]:
X=sampled_data[['carat', 'cut', 'color','clarity']]
y=sampled_data['priceperpoint']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=0, stratify=None) #train,target
print("X_train data: "+str(X_train.shape)) #rows and columns
print("X_test data: "+str(X_test.shape))

X_train data: (23800, 4)
X_test data: (4200, 4)


# 看離散數值+類別

In [23]:
X=sampled_data[['carat_discrete', 'cut', 'color','clarity']]
y=sampled_data['priceperpoint']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=0, stratify=None) #train,target
print("X_train data: "+str(X_train.shape)) #rows and columns
print("X_test data: "+str(X_test.shape))

X_train data: (23800, 4)
X_test data: (4200, 4)


# 看連續數值+二元化

In [37]:
X=sampled_data.drop(['carat_discrete', 'cut', 'color','clarity', 'priceperpoint'],axis=1)
y=sampled_data['priceperpoint']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=0, stratify=None) #train,target
print("X_train data: "+str(X_train.shape)) #rows and columns
print("X_test data: "+str(X_test.shape))

X_train data: (23800, 21)
X_test data: (4200, 21)


# 看離散數值+二元化

In [31]:
X=sampled_data.drop(['carat', 'cut', 'color','clarity', 'priceperpoint'],axis=1)
y=sampled_data['priceperpoint']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=0, stratify=None) #train,target
print("X_train data: "+str(X_train.shape)) #rows and columns
print("X_test data: "+str(X_test.shape))

X_train data: (23800, 21)
X_test data: (4200, 21)


# model

In [32]:
#Naive Bayer Classification
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

gaussian = GaussianNB() 
gaussian.fit(X_train, y_train)  
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)
print("train data accuracy:",acc_gaussian)

predict=gaussian.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predict))

acc_gaussian = round(gaussian.score(X_test, y_test) * 100, 2)
print("test data accuracy:",acc_gaussian)


from sklearn.metrics import classification_report
print(classification_report(y_test,predict))

precision=precision_score(y_test,predict,average='weighted')
recall=recall_score(y_test,predict,average='weighted')
f1=f1_score(y_test,predict,average='weighted')
print("precision:",precision, "\nrecall:", recall, "\nf1:", f1)

train data accuracy: 58.72
[[885  94  53   0]
 [250 306 410  81]
 [  0 123 234 711]
 [  0  19  37 997]]
test data accuracy: 57.67
              precision    recall  f1-score   support

           1       0.78      0.86      0.82      1032
           2       0.56      0.29      0.39      1047
           3       0.32      0.22      0.26      1068
           4       0.56      0.95      0.70      1053

    accuracy                           0.58      4200
   macro avg       0.56      0.58      0.54      4200
weighted avg       0.55      0.58      0.54      4200

precision: 0.5531211143853788 
recall: 0.5766666666666667 
f1: 0.5386573685669336


In [34]:
#Naive Bayer Classification MultinomialNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

gaussian = MultinomialNB() 
gaussian.fit(X_train, y_train)  
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)
print("train data accuracy:",acc_gaussian)

predict=gaussian.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predict))

acc_gaussian = round(gaussian.score(X_test, y_test) * 100, 2)
print("test data accuracy:",acc_gaussian)


from sklearn.metrics import classification_report
print(classification_report(y_test,predict))

precision=precision_score(y_test,predict,average='weighted')
recall=recall_score(y_test,predict,average='weighted')
f1=f1_score(y_test,predict,average='weighted')
print("precision:",precision, "\nrecall:", recall, "\nf1:", f1)

train data accuracy: 54.96
[[624 264  83  61]
 [140 430 307 170]
 [ 18 148 671 231]
 [  0 110 364 579]]
test data accuracy: 54.86
              precision    recall  f1-score   support

           1       0.80      0.60      0.69      1032
           2       0.45      0.41      0.43      1047
           3       0.47      0.63      0.54      1068
           4       0.56      0.55      0.55      1053

    accuracy                           0.55      4200
   macro avg       0.57      0.55      0.55      4200
weighted avg       0.57      0.55      0.55      4200

precision: 0.5678498449058136 
recall: 0.5485714285714286 
f1: 0.5518245757486568


In [38]:
#SVM
from sklearn.svm import SVC, LinearSVC

linear_svc = LinearSVC(penalty='l1',dual=False)
linear_svc.fit(X_train, y_train)
acc_linear_svc = round(linear_svc.score(X_train, y_train) * 100, 2)
print("train data accuracy:",acc_linear_svc)


predict = linear_svc.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predict))

acc_linear_svc = round(linear_svc.score(X_test, y_test) * 100, 2)
print("test data accuracy:",acc_linear_svc)


from sklearn.metrics import classification_report
print(classification_report(y_test,predict))

precision=precision_score(y_test,predict,average='weighted')
recall=recall_score(y_test,predict,average='weighted')
f1=f1_score(y_test,predict,average='weighted')
print("precision:",precision, "\nrecall:", recall, "\nf1:", f1)

train data accuracy: 77.69
[[993  39   0   0]
 [247 567 232   1]
 [  0 179 666 223]
 [  1   6  47 999]]
test data accuracy: 76.79
              precision    recall  f1-score   support

           1       0.80      0.96      0.87      1032
           2       0.72      0.54      0.62      1047
           3       0.70      0.62      0.66      1068
           4       0.82      0.95      0.88      1053

    accuracy                           0.77      4200
   macro avg       0.76      0.77      0.76      4200
weighted avg       0.76      0.77      0.76      4200

precision: 0.7593078585759271 
recall: 0.7678571428571429 
f1: 0.7568438591808136


C:\Users\user\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
